### ISSUE TITLE
class Scope should implements Dynamic

### ISSUE THREAD

**Issue by francescoagati** [ajukraine/hxangular#1]
class Scope implements Dynamic

for autocomplete and dynamic fields

**Comment by ajukraine** [comment]
Hm, we can have a DynamicScope, which extends Scope and implements Dynamic. I like the idea to have type safe Scope class. And as fallback you can introduce DynamicScope. What you think about that?

**Comment by francescoagati** [comment]
Yes good idea

----- Messaggio originale -----
Da: "Bohdan Makohin" notifications@github.com
Inviato: ‎01/‎12/‎2014 01:31
A: "ajukraine/hxangular" hxangular@noreply.github.com
Cc: "francesco agati" francescoagati1975@gmail.com
Oggetto: Re: [hxangular] class Scope should implements Dynamic (#1)

Hm, we can have a DynamicScope, which extends Scope and implements Scope. I like the idea to have type safe Scope class. And as fallback you can introduce DynamicScope. What you think about that?
